[package]
name = "mndp-rs"
version = "0.2.0"
license = "MIT"
edition = "2024"
readme = "README.md"
description = "A simple Rust library and CLI tool for discovering MikroTik devices on your local network using the MikroTik Neighbor Discovery Protocol (MNDP)."
keywords = [
    "mikrotik",
    "router",
    "mndp",
]
categories = [
    "network-programming",
]
repository = "https://github.com/s41ful/mndp-rs.git"

[[bin]]
name = "mndp"
path = "cli/main.rs"

[dependencies]
pnet = "0.35.0"
socket2 = "0.6.5"
tokio = { version = "1.53.1", features = ["full"] }
